version: '3.8'

services:
  # Frontend Only
  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    container_name: entropic-frontend-dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    restart: unless-stopped
    networks:
      - entropic-network

networks:
  entropic-network:
    driver: bridge
